version: "3.9"

services:
  ctf1:
    build:
      context: ./CTFs/BufferOverflow
      dockerfile: Dockerfile
      args:
        FLAG: ${CTF1_FLAG}
    ports:
      - "${CTF1_ACCESS}:22"
    networks:
      - shared

  backend:
    env_file:
      - ./.env
    build:
      context: ./Hiscores/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - shared

  frontend:
    build:
      context: ./Hiscores/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - shared

networks:
  shared:
