version: "3.9"

services:
  ctf1:
    build:
      context: ./CTFs/BufferOverflow
      dockerfile: Dockerfile
      args:
        FLAG: ${CTF1_FLAG}
    ports:
      - "${CTF1_ACCESS}:22"
    networks:
      - shared

  ctf2:
    build:
      context: ./CTFs/EncryptionOSINT
      dockerfile: Dockerfile
    ports:
      - "${CTF2_ACCESS}:22"
    networks:
      - shared

  ctf3:
    build:
      context: ./CTFs/Strings
      dockerfile: Dockerfile
    ports:
      - "${CTF3_ACCESS}:22"
    networks:
      - shared

  ctf4:
    build: 
      context: ./CTFs/SQLi
      dockerfile: Dockerfile
    ports:
      - "${CTF4_ACCESS}:8000"
    networks:
      - shared

  backend:
    env_file:
      - ./.env
    build:
      context: ./Hiscores/backend
      dockerfile: Dockerfile
      args:
        PUBLIC_DEPLOY_URL: ${DEPLOY_URL}
    ports:
      - "8080:8080"
    networks:
      - shared

  frontend:
    build:
      context: ./Hiscores/frontend
      dockerfile: Dockerfile
      args:
        PUBLIC_API_URL: ${API_URL}
        PUBLIC_HOST_URL: ${HOST_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - shared

  deployment:
    build:
      context: ./Deployment
      dockerfile: Dockerfile
      args:
        AWS_REGION: ${AWS_REGION}
        AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "5000:5000"
    networks:
      - shared

networks:
  shared: